sudo: false
language: python
script:
- echo "No Script to run"
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: juganville-staging-secret.json
  project: juganville-staging
  default: true
  on: staging
branches:
  only:
  - master
  - staging
before_install:
- openssl aes-256-cbc -K $encrypted_d1a02f5c23a8_key -iv $encrypted_d1a02f5c23a8_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- tar -xzf credentials.tar.gz
