sudo: false
language: python
script:
- echo "No Script to run"
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: juganville-staging-secret.json
  project: juganville-staging
  default: true
  on: staging
branches:
  only:
  - master
  - staging
before_install:
- openssl aes-256-cbc -K $encrypted_4f69bc391da0_key -iv $encrypted_4f69bc391da0_iv
  -in juganville1-ab4dddde7516.json.enc -out juganville1-ab4dddde7516.json -d
